# 1. Configuración de la conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/saludria?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1086548668D@n
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Configuración de Hibernate / JPA
# update: Le dice a Spring Boot que cree las tablas (usuarios y citas) automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
